import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="max-w-4xl mx-auto p-6">
      <h1 className="text-2xl font-bold mb-4">Terms & Conditions</h1>

      <h2 className="text-xl font-semibold mt-6">Electronic Record:</h2>
      <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

      <h2 className="text-xl font-semibold mt-6">Domain Name:</h2>
      <p>The domain name <a href="http://www.catta.in" className="text-blue-500 underline">www.catta.in</a> is owned by CATTA FASHIONS LLP. This Website contains Intellectual Property the use, copy, reproduction, publishing, hosting, transmission, or sharing of which by User or any third party shall amount to a violation of rights of CATTA FASHIONS LLP.</p>

      <h2 className="text-xl font-semibold mt-6">License and Operation:</h2>
      <p>The Website is operated i.e. in charge of, handled, managed, operated, and run by CATTA FASHIONS LLP.</p>

      <h2 className="text-xl font-semibold mt-6">Definitions:</h2>
      <p>For the purpose of the below-mentioned Terms and Conditions of Use of this Website and its features, wherever the context so requires:</p>
      <ul className="list-disc list-inside mb-4">
        <li><strong>“Additional Terms”</strong> shall mean any terms provided in the invoice or on any other documents or illustrations accompanying the product.</li>
        <li><strong>“Applicable Laws”</strong> shall mean all laws of India, ordinances, statutes, rules, orders, decrees, injunctions, licenses, permits, approvals, authorizations, consents, waivers, privileges, agreements, and regulations of any governmental authority having jurisdiction over the relevant matter as such are in effect as of the date hereof or as may be amended, modified, enacted or revoked from time to time hereafter.</li>
        <li><strong>“Intellectual Property”</strong> shall mean trademarks, names, pictures, titles, logos, texts, IP addresses, images, designs, copyrights, and other proprietary materials owned and registered by Euphoric Innovations and licensed to and managed by CATTA FASHIONS LLP.</li>
        <li><strong>“Policies”</strong> shall mean the Privacy Policy, Legal Policy and Disclaimer, and any other policy uploaded onto the Website from time to time including any amendments or revisions made to existing policies as well as this Terms of Use.</li>
        <li><strong>“Terms of Use”</strong> shall mean this Terms and Conditions of Use including any amendments or revisions made from time to time.</li>
        <li><strong>“CATTA FASHIONS LLP”</strong> shall mean CATTA FASHIONS LLP, a company incorporated under the Companies Act, 2013 having its registered office at 11/259, Cherur Road Kazhukanchina, Cherur, PO; Vengara, Malappuram, Kerala, India - PIN 676304.</li>
        <li><strong>“We”, “Us”, “Our”</strong> shall mean CATTA FASHIONS LLP.</li>
        <li><strong>“Website”</strong> shall mean CATTA FASHIONS LLP.in and shall include the homepage and all other webpages and data files connected through hyperlinks excluding any third-party websites on which CATTA FASHIONS LLP does not have any control.</li>
        <li><strong>“You” or “User ”</strong> shall mean any natural or legal person who has agreed to become a casual user who browses through the site, a Registered user/Member who registers by providing requisite details and/or a buyer on the Website.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-6">Interpretation:</h2>
      <p>The terms and conditions of the Policies shall apply unless modified in the Additional Terms. In the event of any conflict between the provisions of the Policies and the Additional Terms, the provisions of the Additional Terms shall prevail.</p>

      <h2 className="text-xl font-semibold mt-6">Applicability:</h2>
      <p>Your use of the Website and services and tools are governed by the following Terms as applicable to the Website including the applicable Policies which are referred to herein. By mere use of the Website, You shall be contracting with us, these Terms including the Policies constitute your binding obligations with Us.</p>

      <h2 className="text-xl font-semibold mt-6">Right to Use and Amendment:</h2>
      <p>We reserve the right, at Our sole discretion, to change, modify, add, or remove portions of these Terms of Use at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates/changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revision.</p>
      <p>As long as You comply with these Terms of Use and other Policies of CATTA FASHIONS LLP as provided on the Website, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.</p>

      <h2 className="text-xl font-semibold mt-6">Acceptance:</h2>
      <p>Browsing or accessing the Website indicates Your agreement to all the Terms of Use. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Our Policies. Hence, please read the Policies carefully before proceeding.</p>

      <h2 className="text-xl font-semibold mt-6">Eligibility:</h2>
      <p>Use of the Website for placing online orders is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors (below the age of 18 years), un-discharged insolvents etc. are not eligible to use the Website. If you are incompetent to contract under Indian Contract Act, 1872 as provided above, you shall not register as a User of the Website and shall not transact on or use the Website.</p>
      <p>As a minor if you wish to use or transact on Website, such use or transaction may be made by Your legal guardian or parents on the Website who agree to be bound by the Terms of Use of the Website and responsible for any consequences or implications of a minor using the Website without adult supervision.</p>
      <p>We reserve the right to terminate Your membership and/or refuse to provide you access to the Website if it is brought to Our notice or if it is discovered that you are incompetent to contract under Indian Contract Act, 1872 as provided above.</p>

      <h2 className="text-xl font-semibold mt-6">User  Obligations:</h2>
      <p>You agree to use the Website and the materials provided therein only for purposes that are permitted by:</p>
      <ul className="list-disc list-inside mb-4">
        <li>The Terms of Use and other Policies.</li>
        <li>Any Applicable Laws.</li>
      </ul>
      <p>You agree to adhere to all limitations on dissemination, use and reproduction of any materials (such as the product catalogues) that You access on the Website in accordance with the Policies.</p>
      <p>You agree not to access (or attempt to access) the Website and the materials or services by any means other than through the interface that is provided by Us. You shall not use any deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or Intellectual Property, or in any way reproduce or circumvent the navigational structure or presentation of the Website, materials or any Content, to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Website.</p>
      <p>You acknowledge and agree that by accessing or using the Website or Services, You may be exposed to content from other users that You may consider offensive, indecent or otherwise objectionable. CATTA FASHIONS LLP disclaims all liabilities arising in relation to such offensive content on the Website. Further, You may report such offensive content at the email address <a href="mailto:cattafashion@gmail.com" className="text-blue-500 underline">cattafashion@gmail.com</a>.</p>

      <h2 className="text-xl font-semibold mt-6">Prohibited Actions:</h2>
      <p>You shall not host, display, upload, modify, publish, transmit, update or share any information which:</p>
      <ul className="list-disc list-inside mb-4">
 <li>Belongs to another person and to which You do not have any right to.</li>
        <li>Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to ‘indecent representation of women’ within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986.</li>
        <li>Is misleading in any way.</li>
        <li>Is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophilia, racism, bigotry, vengeance, hatred or physical harm of any kind against any group or individual.</li>
        <li>Harasses or advocates harassment of another person.</li>
        <li>Involves the transmission of ‘junk mail’, ‘chain letters’, or unsolicited mass mailing or ‘spamming’.</li>
        <li>Infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address, or phone number), or rights of publicity].</li>
        <li>Promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files.</li>
        <li>Contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page).</li>
        <li>Provides material that exploits people in a sexual, violent, or otherwise inappropriate manner or solicits personal information from anyone.</li>
        <li>Tries to gain unauthorized access or exceeds the scope of authorized access to the Website or to profiles, blogs, communities, account information, bulletins, friend requests, or other areas of the Website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users.</li>
        <li>Engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products related to the Website.</li>
        <li>Interferes with another User's use and enjoyment of the Website or any other individual's User and enjoyment of similar services;</li>
        <li>Refers to any Website or URL that, in Our sole discretion, contains material that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.</li>
        <li>Harm minors in any way.</li>
        <li>Infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products.</li>
        <li>Violates any law for the time being in force.</li>
        <li>Impersonate another person.</li>
        <li>Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, cancelbots or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information.</li>
        <li>Threatens the unity, integrity, defense, security, or sovereignty of India, friendly relations with foreign states, or public order.</li>
        <li>Is false, inaccurate or misleading.</li>
        <li>Shall be directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any Applicable Laws.</li>
        <li>Shall create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider (‘ISPs’) or other suppliers.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-6">Access to Website:</h2>
      <p>We will do Our utmost to ensure that availability of the Website will be uninterrupted and that transmissions will be error-free. However, due to the nature of internet, this cannot be guaranteed. Also, Your access to the Website may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction.</p>

      <h2 className="text-xl font-semibold mt-6">Confidentiality:</h2>
      <p>As a registered User (member) you are responsible for maintaining the confidentiality of user-id and password and you shall be responsible for all activities that occur under Your user-id. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or if We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or if not in accordance with the stipulated Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of Your membership on the Website and refuse to provide You with access to the Website.</p>

      <h2 className="text-xl font-semibold mt-6">Communication:</h2>
      <p>When You use the Website or send emails, information or communication to Us, You understand that You are communicating with Us through electronic records and You also consent to receive communications via electronic records from Us periodically and as and when required.</p>

      <h2 className="text-xl font-semibold mt-6">Price:</h2>
      <p>Registration / Membership on the Website is free. We do not charge for browsing or buying on this Website. The prices of products displayed in the Website are the maximum retail price (MRP) only and may vary from time to time. Unless otherwise specified, all prices mentioned are in Indian Rupees.</p>
      <p>The prices and products are subject to change from time to time at Our discretion. All prices of products displayed on the Website are inclusive of applicable taxes. CATTA FASHIONS LLP may at its sole discretion offer discounts to the customers on their purchases.</p>
      <p>The Users shall be solely responsible for compliance of all Applicable Laws for making payments on orders through the Website.</p>
      <p>We shall not be responsible for any service charges and related taxes levied on You for the use of any payment and settlement mechanism or use of any specific bank for facilitating the payment and any such additional payments made by You shall be in addition to the price paid for purchase of the product.</p>
      <p>The Website will not facilitate transaction with respect to any other form of currency with respect to the purchases made on Website. Unless otherwise specified, the products on this Website are presented solely for the purpose of sale in India.</p>
      <p>We make no representation that materials in the Website are appropriate or available for use in other locations / countries other than India.</p>
      <p>Those who choose to access this Website from other locations / countries other than India do so on their own initiative and we are not responsible for supply of products ordered from countries other than India.</p>
      <p>Pricing on any product(s) as is reflected on the Website may due to some technical issue, typographical error or product information published by CATTA FASHIONS LLP may be incorrectly reflected and in such an event CATTA FASHIONS LLP may cancel Your order(s).</p>

      <h2 className="text-xl font-semibold mt-6">Payment:</h2>
      <p>For the purpose of online ordering and payment, all Valid Credit / Debit/ Cash Card/ and other payment instruments are processed using a Credit Card payment gateway or appropriate payment system infrastructure and the same will also be governed by the terms and conditions agreed to between You and the respective issuing bank / payment instrument issuing company.</p>
      <p>All the online bank transfers from valid bank accounts are processed using the gateway provided by the respective issuing bank which supports payment facility to provide these services to the Users. All such online bank transfers on payment facility are also governed by the terms and conditions agreed to between You and the respective issuing bank.</p>
      <p>While availing any of the payment method/s available on the Website, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:</p>
      <ul className="list-disc list-inside mb-4">
        <li>Lack of authorization for any transaction/s, or</li>
        <li>Exceeding the preset limit mutually agreed by You and between Your issuing bank or payment facility, or</li>
        <li>Any payment issues arising out of the transaction, or</li>
        <li>Decline of transaction for any other reason/s.</li>
      </ul>
      <p>All payments made against the purchases on the Website by You shall be compulsorily in Indian Rupees acceptable in the Republic of India. We will not facilitate transactions with respect to any other form of currency with respect to the purchases made on the Website. Before shipping/delivering Your order to You, CATTA FASHIONS LLP may request You to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by You for Your purchase. This is done in the interest of providing a safe online shopping environment to Our Users.</p>

      <h2 className="text-xl font-semibold mt-6">Shipment:</h2>
      <p>The shipping of products from Our end to the customer will be effected through third-party courier agencies with whom We have contracted separately. The title and risk of loss for all products ordered by You shall pass on to You upon Our shipment to the courier. The courier will make a maximum of three attempts to deliver Your order. In case You are not reachable or You do not accept delivery of products in these attempts we reserve the right to cancel the order(s) at Our discretion.</p>

      <h2 className="text-xl font-semibold mt-6">Necessary Infrastructure:</h2>
      <p>You shall solely be responsible for maintaining the necessary computer equipment and Internet connections that may be required to access, use and transact on the Website.</p>

      <h2 className="text-xl font-semibold mt-6">Violation of the Terms of Use:</h2>
      <p>You agree that We may, in Our sole discretion and without prior notice, terminate Your access to the Website and block Your future access to the Website if We determine that You have violated these Terms of Use or Additional Terms. You also agree that any violation by You of these Terms of Use will constitute an unlawful and unfair business practice, and will cause irreparable harm to CATTA FASHIONS LLP, for which monetary damages would be inadequate, and You consent to CATTA FASHIONS LLP obtaining any injunctive or equitable relief that CATTA FASHIONS LLP deems necessary or appropriate in such circumstances. These remedies are in addition to any other remedies CATTA FASHIONS LLP may have at law or in equity.</p>

      <h2 className="text-xl font-semibold mt-6">Termination:</h2>
      <p>The Terms of Use will continue to apply and survive indefinitely until terminated by either You or Us as set forth below. If You want to terminate Your agreement with Us, You may do so by not accessing the Website; or closing Your accounts for all of the services that You use, where We have made this option available to You on the Website.</p>
      <p>We may, at any time, with or without notice, terminate the Terms of Use (or portion thereof) with You if:</p>
      <ul className="list-disc list-inside mb-4">
        <li>You breach any of the provisions of the Terms of Use or any terms and conditions of the other Policies that may be applicable to You from time to time or have acted in a manner that clearly shows that You do not intend to, or are unable to, comply with the same.</li>
        <li>We are required to do so by Applicable Laws (for example, where the provision of services to You is, or becomes, unlawful);</li>
        <li>The provision of the services to You by Us is, in Our sole opinion, no longer commercially viable.</li>
        <li>We have elected to discontinue, with or without reason, access to the Website, the services provided through the Website (or any part thereof); or</li>
        <li>We may also terminate or suspend all or a portion of Your account or access to the Website with or without reason.</li>
      </ul>
      <p>You agree that all terminations shall be made in Our sole discretion and that CATTA FASHIONS LLP shall not be liable to You or any third party for any termination of Your account (and accompanying deletion of Your account information), or Your access to the Website and services provided through the Website.</p>

      <h2 className="text-xl font-semibold mt-6">Limitation of Liability:</h2>
      <p>We will not be responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered. We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any transaction, on account of having exceeded the preset limit mutually agreed by you with the bank or, any other payment issues arising out of the transaction.</p>
      <p>We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to You and Us in the course of Your using the Website.</p>
      <p>We will not be held responsible for any delay or failure to comply with Our obligations under these Policies if the delay or failure arises from any cause which is beyond Our reasonable control.</p>
      <p>In any case, Our liability shall in no circumstances exceed the extent of the price paid by You or intended to be paid by You for purchasing a product through the Website in the disputed transaction.</p>

      <h2 className="text-xl font-semibold mt-6">Indemnity:</h2>
      <p>You release, indemnify and hold harmless CATTA FASHIONS LLP and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions/inactions of the Users of the Website and specifically waive any claims that You may have in this behalf under any contract, Applicable Laws or otherwise.</p>
      <p>Notwithstanding its reasonable efforts in that behalf, CATTA FASHIONS LLP cannot take responsibility or control the information provided by other Users which is made available on the Website. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Website. Please note that there could be risks in dealing with underage persons or people acting under false pretense. CATTA FASHIONS LLP shall not be liable for any action/inaction of the third party in relation to the Website.</p>
      <p>You shall indemnify and hold harmless CATTA FASHIONS LLP and its affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney’s fees, made by any third party or penalty imposed due to or arising out of Your breach of these Terms of Use or any document incorporated by reference, or Your violation of any law, rules, regulations or the rights of a third party.</p>

      <h2 className="text-xl font-semibold mt-6">Damages:</h2>
      <p>In the process of effecting the online ordering facility through this Website, we have endeavoured to ensure that all efforts have been taken to provide quality and reliable service through various third party service providers, but we neither warrant nor make any representations regarding the quality, accuracy or completeness of the service provided through the Website.</p>
      <p>In no event shall We be liable for any direct, indirect, punitive, incidental, special, consequential damages or any other damages resulting from the use or the inability to use the services of the Website, from the unauthorized access to or alteration of the User's transmissions or data, or from any other matter relating to the services including, without limitation, damages for loss of use or data, arising out of or in any way connected with the use or performance of the Website or services provided through the Website.</p>

      <h2 className="text-xl font-semibold mt-6">User  Website Content:</h2>
      <p>As per these Terms of Use, Users are solely responsible for every material or content uploaded on to the Website. We do not review the contents in any way before they appear on the Website. Users can be held legally liable for their contents and may be held legally accountable if their contents or material include, for example, defamatory comments or material protected by copyright, trademark, etc.</p>
      <p>You shall be responsible for any notes, messages, emails, billboard postings, photos, drawings, designs, profiles, opinions, reviews, ideas, images, videos, audio files or other materials or information posted or transmitted to the Website (collectively, ‘User  Content’). Such Content will become Our property and You grant Us the worldwide, perpetual and transferable rights in such User Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with Applicable Laws, use the User Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the User Content You provide. You agree that any User Content You post may be used by Us, consistent with Our Privacy Policy and that You are not entitled to any payment or other compensation for such use.</p>
      <p>It is possible that other Users (including unauthorized Users or ‘hackers’) may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to Your use of the Website, and that the recipient may use such information to harass or injure You. We do not approve of such unauthorized uses, but by using the Website, You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that You publicly disclose or share with others on the Website.</p>

      <h2 className="text-xl font-semibold mt-6">Copyright:</h2>
      <p>Except as expressly provided in here, no part of the Website and no content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including ‘mirroring’) to any other computer, server, Website or other medium for publication or distribution or for any commercial enterprise, without Our express prior written consent.</p>
      <p>This Website or any portion of this Website (including but not limited to any Intellectual Property or other copyrighted material, trademarks, or other proprietary information) shall not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without express written consent of CATTA FASHIONS LLP.</p>
      <p>You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of CATTA FASHIONS LLP and its affiliates without express written consent. You may not use any meta tags or any other ‘hidden text’ utilizing CATTA FASHIONS LLP’s names or trademarks without the express written consent of CATTA FASHIONS LLP. Any unauthorized use terminates the permission or license granted by CATTA FASHIONS LLP and CATTA FASHIONS LLP shall take stringent action against any breach of Intellectual Property rights of CATTA FASHIONS LLP.</p>
      <p>You are granted a limited, revocable, and non-exclusive right to create a hyperlink to the Welcome page of the Website as long as the link does not portray CATTA FASHIONS LLP, Website, CATTA FASHIONS LLP or their products or services in a false, misleading, derogatory, or otherwise offensive matter. Providing such a link to the Website shall not create a relationship of agency or partnership between You and CATTA FASHIONS LLP and shall not entitle You to any financial incentive or remuneration from CATTA FASHIONS LLP or CATTA FASHIONS LLP.</p>

      <h2 className="text-xl font-semibold mt-6">Content Download:</h2>
      <p>You may download one single hard copy of contents displayed on the Site for non-commercial, personal use only, provided however, you do not delete or change the copyright, trademark and other proprietary notices contained therein.</p>
      <p>You may not modify, alter or change any Intellectual Property Materials or distribute, publish, transmit, reuse, re-post or use the content of the website for public or commercial purposes, including, without limitation, the text, images, audio and video.</p>
      <p>You may use information on the products and services purposely made available on the Website for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for Your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents.</p>
      <p>The User acknowledges that CATTA FASHIONS LLP has proprietary rights on the design of the footwear and the User shall not use, copy, reproduce or modify to create other design of any footwear displayed on the Website.</p>

      <h2 className="text-xl font-semibold mt-6">Applicable Laws:</h2>
      <p>These Terms of Use shall be governed by and constructed in accordance with the Applicable laws of India without reference to conflict of laws principles and disputes arising in relation hereto shall be subject to the exclusive jurisdiction of the courts at Kozhikode. You shall comply with all the Applicable Laws while using Website and Website’s payment facility.</p>

      <h2 className="text-xl font-semibold mt-6">Reporting Violation:</h2>
      <p>If you come across any abuse or violation of these Terms of Use, please report to Us at Our contact address provided.</p>

      <h2 className="text-xl font-semibold mt-6">Waiver:</h2>
      <p>If you breach these conditions and we take no action, we will still be entitled to use Our rights and remedies in any other situation where you breach these conditions.</p>

      <h2 className="text-xl font-semibold mt-6">Severability:</h2>
      <p>If any provision of the Terms of Use is determined to be invalid or unenforceable in whole or in part, such invalidity or unenforceability shall attach only to such provision or part of such provision and the remaining part of such provision and all other provisions of these Terms of Use shall continue to be in full force and effect.</p>

      <h2 className="text-xl font-semibold mt-6">Grievance Officer:</h2>
      <p>In the event You suffer as a result of access or usage of the Website by any person in violation of the Policies kindly notify the grievance officer appointed under Rule 3(11) of Information Technology (Intermediaries guidelines) Rules, 2011 at the contact information below:</p>
      <p>CATTA FASHIONS LLP<br />
      11/259, Cherur Road Kazhukanchina,<br />
      Cherur, PO; Vengara, Malappuram, Kerala<br />
      India - PIN 676304<br />
      Contact Us: +91 90613 95430<br />
      Email: <a href="mailto:cattafashion@gmail.com" className="text-blue-500 underline">cattafashion@gmail.com</a></p>
    </div>
  );

};

export default TermsAndConditions;